# Generated by Django 4.0.4 on 2022-05-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_delete_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telephone number'),
        ),
    ]
